sudo: false

language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get install build-essential git libssl-dev unixodbc-dev libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev
addons:
  apt:
    update: true

install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"

before_script: cd $TRAVIS_BUILD_DIR/core/release

script:
  - ./buil.sh 64